#include "testscreenwindow.h"
#include "ui_testscreenwindow.h"

TestScreenWindow::TestScreenWindow(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::TestScreenWindow)
{
    ui->setupUi(this);
    this->fullTestConfiguration = new FullTestConfiguration();
    QList <QPushButton *> buttons = this->fullTestConfiguration->getButtons(this);


    //configuration -> steps -> rows -> cols

}

TestScreenWindow::~TestScreenWindow()
{
    delete ui;
}


FullTestConfiguration::FullTestConfiguration() {
    currentStep = 0;
    addConfiguration((new TestConfiguration("gray"))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#bbbbbb", 0))
                            ->addItem(TestColorItem())
                            ->addItem(TestColorItem("#ffffff", 1)))
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem())
                            ->addItem(TestColorItem("#888888", 2))
                            ->addItem(TestColorItem()))
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#000000", 3))
                            ->addItem(TestColorItem())
                            ->addItem(TestColorItem("#404040", 4))))
    );
    addConfiguration((new TestConfiguration("want"))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#94989b", 0))
                            ->addItem(TestColorItem("#014983", 1))
                            ->addItem(TestColorItem("#017477", 2))
                            ->addItem(TestColorItem("#eb1b31", 3)))
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#fee600", 4))
                            ->addItem(TestColorItem("#d80081", 5))
                            ->addItem(TestColorItem("#9d685a", 6))
                            ->addItem(TestColorItem("#231f20", 7))))
    );
    addConfiguration((new TestConfiguration("color"))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#014983", 0))
                            ->addItem(TestColorItem("#fee600", 1))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#017477", 2))
                            ->addItem(TestColorItem("#950000", 3))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#014983", 0))
                            ->addItem(TestColorItem("#017477", 2))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#950000", 3))
                            ->addItem(TestColorItem("#fee600", 1))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#014983", 0))
                            ->addItem(TestColorItem("#950000", 3))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#017477", 2))
                            ->addItem(TestColorItem("#fee600", 1))))
    );
    addConfiguration((new TestConfiguration("blue"))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#002948", 0))
                            ->addItem(TestColorItem("#0080ff", 1))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#017477", 2))
                            ->addItem(TestColorItem("#8080ff", 3))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#002948", 0))
                            ->addItem(TestColorItem("#017477", 2))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#8080ff", 3))
                            ->addItem(TestColorItem("#0080ff", 1))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#002948", 0))
                            ->addItem(TestColorItem("#8080ff", 3))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#017477", 2))
                            ->addItem(TestColorItem("#0080ff", 1))))
    );
    addConfiguration((new TestConfiguration("green"))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#364600", 0))
                            ->addItem(TestColorItem("#629102", 1))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#017477", 2))
                            ->addItem(TestColorItem("#01652c", 3))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#364600", 0))
                            ->addItem(TestColorItem("#017477", 2))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#01652c", 3))
                            ->addItem(TestColorItem("#629102", 1))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#364600", 0))
                            ->addItem(TestColorItem("#01652c", 3))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#017477", 2))
                            ->addItem(TestColorItem("#629102", 1))))
    );
    addConfiguration((new TestConfiguration("red"))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#783f10", 0))
                            ->addItem(TestColorItem("#b97715", 1))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#812e12", 2))
                            ->addItem(TestColorItem("#950000", 3))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#783f10", 0))
                            ->addItem(TestColorItem("#812e12", 2))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#950000", 3))
                            ->addItem(TestColorItem("#b97715", 1))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#783f10", 0))
                            ->addItem(TestColorItem("#950000", 3))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#812e12", 2))
                            ->addItem(TestColorItem("#b97715", 1))))
    );
    addConfiguration((new TestConfiguration("yellow"))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#a36016", 0))
                            ->addItem(TestColorItem("#fee600", 1))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#336f1a", 2))
                            ->addItem(TestColorItem("#b34917", 3))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#a36016", 0))
                            ->addItem(TestColorItem("#336f1a", 2))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#b34917", 3))
                            ->addItem(TestColorItem("#fee600", 1))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#a36016", 0))
                            ->addItem(TestColorItem("#b34917", 3))))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#336f1a", 2))
                            ->addItem(TestColorItem("#fee600", 1))))
    );
    addConfiguration((new TestConfiguration("real"))
            ->addStep((new TestStep())
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#9d685a", 6))
                            ->addItem(TestColorItem("#014983", 1))
                            ->addItem(TestColorItem("#94989b", 0))
                            ->addItem(TestColorItem("#017477", 2)))
                    ->addStepRow((new TestStepRow())
                            ->addItem(TestColorItem("#eb1b31", 3))
                            ->addItem(TestColorItem("#fee600", 4))
                            ->addItem(TestColorItem("#231f20", 7))
                            ->addItem(TestColorItem("#d80081", 5)))));


}
