version: '2'
services:
    nginx:
        build: ./images/nginx/
        links:
            - fpm
#        ports:
#            - 8200:80
        volumes:
            - ./app/system/nginx/:/data/config/
            - ./app:/data/project

    fpm:
        build: ./images/php/
        links:
            - mariadb
        volumes:
            - ./app:/data/project

    mariadb:
        image: mariadb:latest
        environment:
            - MYSQL_DATABASE=mydb
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=docker

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:mysql
        environment:
            - PMA_HOST=mysql
            - MYSQL_USERNAME=root
            - MYSQL_ROOT_PASSWORD=docker

