version: '2'
services:
    nginx:
        build: ./images/nginx/
        links:
            - fpm
        ports:
            - 8200:80
        volumes:
            - ./system/nginx/:/data/config/
            - .:/data/project

    fpm:
        build: ./images/php/
        links:
            - mariadb
        volumes:
            - .:/data/project

    mariadb:
        image: mariadb:latest
        environment:
            - MYSQL_DATABASE=mydb
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=docker

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:mysql
        environment:
            - PMA_HOST=mysql
            - MYSQL_USERNAME=root
            - MYSQL_ROOT_PASSWORD=docker

